
// @ts-nocheck

// This file is automatically generated.
// Do not edit this file directly.
// Last generated: 2024-05-22T19:23:42.535Z

export const firebaseConfig = {
    apiKey: "AIzaSyD534ZsitCt9lO7iRYbvhZJGaiKU_bghsI",
    authDomain: "gen-lang-client-0905155605.firebaseapp.com",
    projectId: "gen-lang-client-0905155605",
    storageBucket: "gen-lang-client-0905155605.appspot.com",
    messagingSenderId: "391099279839",
    appId: "1:391099279839:web:93f7b9bf783bace6d9fc6a",
    measurementId: "G-MKBDZ409SH"
  };
